<a href="https://colab.research.google.com/github/sushanttwayana/PYTHON/blob/main/Working_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Cumulative Product

def cum_product(list):
  p = 1

  for i in list :
    p *= i
    print(p)

list1= [1, 3, 5, 7, 9]
cum_product(list1)

1
3
15
105
945


In [3]:
# Checking Duplicates in thel list

def check_duplicates(list):
   flag = 0

   for elem in list:

      counter = list.count(elem)

      if counter > 1:
        flag = 1
        break

   if flag == 1:
      print("There exists duplicate elements in the list")

   else :
    print ("No duplicates exists in the list")


list1 = [1, 2, 3, 4 ,5 ,6 ,7, 8]
check_duplicates(list1)


No duplicates exists in the list


In [7]:

def check_duplicates(list):
   flag = 0
   list2 = []

   for elem in list:
      counter = list.count(elem)

      if counter > 1 and elem not in list2:
        list2.append(elem)

   print("the repeated elements of the list are:", list2)

list1 = [1, 2, 3, 2 ,5 ,6 ,7, 7,0 , 1]
check_duplicates(list1)

the repeated elements of the list are: [1, 2, 7]


In [9]:
# gcd of two numbers

import math

a = int(input("Enter first number:"))
b = int(input("Enter second number:"))

result = math.gcd(a, b)
print("GCD of %d and %d is %d" %(a, b, result))


Enter first number:100
Enter second number:20
GCD of 100 and 20 is 20


In [ ]:

# NumPy (Numerical Python) is a fundamental library in Python used for numerical and scientific computing. It provides support for large,
#  multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.
#   NumPy is a crucial building block for data analysis, scientific computing, and machine learning in Python.

In [11]:
# creating and accessing 1D array

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print("First Element:", arr[0])
print("Second Element:", arr[1])

[1 2 3 4 5]
First Element: 1
Second Element: 2


In [13]:
# creating and accessing 1D array

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

print(arr[0][0])
print(arr[0][1])
print(arr[0][2])
print(arr[1][0])

[[1 2 3]
 [4 5 6]]
1
2
3
4


In [15]:
# identify dimension of array

import numpy as np

b = np.array([[1,2,3], [8, 9, 0]])

# arrayname.ndim

print("The dimension is:", b.ndim)

The dimension is: 2


In [16]:
# negative indexing of an array

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[-1])

5


In [21]:
# negative indexing of an array 2D array

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0][-1])
print(arr[1][-1])

5
10


In [24]:
# slicing of an array
# if statring index is not given it is considered as zero and for ending index not given it will consider len(array)
# for default step-size is 1
# [start : end : step-size]

import numpy as np

arr = np.array([1, 3, 5, 7 ,9,11, 12])

print(arr[1 : 5])
print(arr[4 : ])
print(arr[1 : 5 : 2]) # dispaly less than index 5

[3 5 7 9]
[ 9 11 12]
[3 7]


In [25]:
import numpy as np

a = np.array([1, 2, 3 , 6])

print(a.dtype)

int64


In [28]:
import numpy as np

# Create a list of Python objects
objects_list = [1, 'apple', [1, 2, 3], {'name': 'John', 'age': 30}]


# Create a NumPy object array
obj_array = np.array(objects_list, dtype=object)

# datatype

print(obj_array.dtype)

# Print the NumPy object array
print(obj_array)


object
[1 'apple' list([1, 2, 3]) {'name': 'John', 'age': 30}]


In [32]:
# Copy contents of  aray

import numpy as np

a = np.array([1, 2, 3 , 4, 6])
# x = a.copy()
a[0] = 10
x = a.copy()
print("Contents of array a is:", a)
print("Contents of array x is:", x)

Contents of array a is: [10  2  3  4  6]
Contents of array x is: [10  2  3  4  6]


In [34]:
# Iterate 1D array

import numpy as np

arr = np.array([1,2, 3, 4 ,5])

for i in arr:

  print(i, end = " ")

1 2 3 4 5 

In [36]:
# Iterate 2D array

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
  print(i)

[1 2 3]
[4 5 6]


In [38]:
# Finding shape of the array

import numpy as np

arr1 = np.array([[1, 2, 3, 4], [ 5, 6, 7 ,8]])

print(arr1.shape)



(2, 4)


In [45]:
# Reshaping 1D to 2D

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6 ,7 ,8 ,9, 10, 11, 12])

b = a.reshape(3, 4)

print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
# Joining two arrays

import numpy as np

x = np.array([1, 3, 5, 7 ,9])
y = np.array([0, 2, 4, 6 ,8])

z = np.concatenate( (x, y) )

print(z)

[1 3 5 7 9 0 2 4 6 8]


In [53]:
# spliting of an array
import numpy as np

arr = np.array([1 ,3 ,5 ,7 ,9 ,0 ,2 ,4 ,6, 8])

arr2 = np.array_split(arr, 6)

print(arr2)

[array([1, 3]), array([5, 7]), array([9, 0]), array([2, 4]), array([6]), array([8])]


In [54]:
# sorting of an array

import numpy as np

arr = np.array([1 ,3 ,5 ,7 ,9 ,0 ,2 ,4 ,6, 8])

print(np.sort(arr))

[0 1 2 3 4 5 6 7 8 9]


In [56]:
# sorting of an array

import numpy as np

arr = np.array(['cat', 'bat', 'ant'])

print(np.sort(arr))

arr1 = np.array([[6, 2, 3], [9, 3, 6]])

print(np.sort(arr1))

['ant' 'bat' 'cat']
[[2 3 6]
 [3 6 9]]


In [60]:
# Searching of an element in an array

import numpy as np

arr = np.array([1 ,3 ,5 ,7 ,9 ,0 ,2 ,4 ,6, 8, 4])

# arr = np.sort(arr)
# print(arr)

x = np.where(arr == 4)

print(x)

(array([ 7, 10]),)


In [62]:
# Find the indices where the values are even

import numpy as np

arr = np.array([10, 1 ,3 ,5 ,7 ,9 ,0 ,2 ,4 ,6, 8, 4])

x = np.where(arr % 2 == 0)
print(x)

(array([ 0,  6,  7,  8,  9, 10, 11]),)


In [63]:
# Filtering elements of an arrray

import numpy as np
arr = np.array([1 ,3 ,5 ,7])

# using boolean index list -> filtering is done

x = [True, False, True, False]

new_arr = arr[x]
print(new_arr)



[1 5]


In [66]:
# Gernerate random integer

from numpy import random

x = random.randint(100)
print(x)

48


In [68]:
# Generate random array

from numpy import random

for i in range(5):

  x = random.randint(100, size = (5))
  print(x)



[28 54 83 31 35]
[86 55  9  7 14]
[ 2 72 88  2 40]
[81 80 21 13 37]
[87  2 89 32 14]


In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [71]:
import numpy as np

# Create a 3D array
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ],
    [
        [13, 14, 15],
        [16, 17, 18],
    ]
])

# Print the 3D array
print(arr)

print(arr[0, 1, 2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
6


In [73]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5 , 6, 7])

print(arr[::2])

[1 3 5 7]


In [74]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6,7, 8 ,9, 10, 11, 12])

new_arr = arr.reshape(2, 3, 2)

print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
